# Part of the io_threads project (https://github.com/cpp4ever/io_threads), under the MIT License
# SPDX-License-Identifier: MIT
#
# Copyright (c) 2024 Mikhail Smirnov
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: Windows

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build:
    name: "${{matrix.os}} ${{matrix.platform}} ${{matrix.toolset}} ${{matrix.ssl-library}} ${{matrix.build-type}}"
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false
      matrix:
        build-type: [Debug, Release]
        os: [windows-2019, windows-2022]
        platform: [Win32, x64]
        ssl-library: [openssl, schannel]
        toolset: [v142, v143, ClangCL]
        exclude:
          - toolset: v142
            os: windows-2022
          - toolset: v143
            os: windows-2019
          - toolset: ClangCL
            os: windows-2019
          - ssl-library: openssl
            platform: Win32

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Install CMake
      run: |
        cmake --version
        cmake -E make_directory ${{runner.workspace}}/build

    - name: Install openssl
      if: ${{matrix.ssl-library == 'openssl'}}
      run: |
        choco install openssl
        xcopy /d /e /f /h /i /k /o /q /r /s /v /x /y "C:\Program Files\Git\usr\ssl\*" "C:\Program Files\Common Files\SSL\"

    - name: Configure
      working-directory: ${{runner.workspace}}/build
      run: |
        echo "CMAKE_BUILD_PARALLEL_LEVEL=$((Get-CimInstance Win32_ComputerSystem).NumberOfLogicalProcessors)" >> $env:GITHUB_ENV
        echo "CTEST_OUTPUT_ON_FAILURE=1" >> $env:GITHUB_ENV
        cmake -A ${{matrix.platform}} -DIO_THREADS_SSL_LIBRARY=${{matrix.ssl-library}} -DIO_THREADS_SANITIZER=ASan -T ${{matrix.toolset}} -S ${{github.workspace}}

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: |
        cmake --build . --config ${{matrix.build-type}} --target io_threads_tests

    - name: Test
      working-directory: ${{runner.workspace}}/build
      run: |
        ctest --build-config ${{matrix.build-type}} --output-on-failure
